config/routes.rb
Rails.application.routes.draw do
  root :to => 'welcome#index'
  resources :welcome  
  
  resources :categories do
    resources :products, :controller => 'category_products'
  end
  
  resources :users

  namespace :admin do
    resource :login, only: [:new, :create, :destroy]
    resources :categories do
      resources :products, :controller => 'category_products'
    end
  end
  

end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/admin/category.rb
class Admin::Category < Category
end

app/models/admin/product.rb
class Admin::Product < Product
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products
	validates_presence_of :title
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	belongs_to :product
	has_attached_file :file, :style => {:medium => "300x300#", :thumb => "100x100#"}
	validates_attachment_content_type :file, :content_type => /\Aimage\/.*\Z/
end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :category
	has_many :photos
	
	# 商品圖片
	has_attached_file :image, :styles => {:medium => "300x300#", :thumb => "100x100#"}
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
	
	# 價錢須為整數
	validates_numericality_of :price, :only_integer => true
	validates_presence_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	before_save {self.login_token ||= Digest::SHA1.hexdigest(SecureRandom.urlsafe_base64.to_s)}
	validates :name, presence: true, length: {maximum: 15}
	validates :account, presence: true, length: {maximum: 15}, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include Admin::LoginsHelper
  include CategoriesHelper
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :sidebar_categories
  layout "categories"
end

app/controllers/category_products_controller.rb
class CategoryProductsController < ApplicationController
	before_action :sidebar_categories
	before_action :find_category
	layout "categories"

	def index
		@products = @category.products.page(params[:page]).per(9)
	end

	def show
		@product = @category.products.find(params[:id])
	end

protected
	def find_category
		@category = Category.find(params[:category_id])
	end
	
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def show

	end

	def create
		@user = User.new(user_params)
		if @user.save
			flash[:success] = "Welcome, #{@user.name}!"
			redirect_to admin_categories_path
		else	
			flash[:error] = "There are #{@user.errors.count} errors, #{@user.errors.full_messages}" 
			render action: 'new'
		end
	end

	def edit
		
	end

	def update
		if params[:user][:new_password] == params[:user][:password_confirmation]
			if current_user.authenticate(params[:user][:password])
				current_user.password = params[:user][:new_password]
				if current_user.save
					flash[:success]	= "您已成功修改密碼"
					redirect_to admin_categories_path
				end
			else		
				flash[:error] = "您輸入的密碼不正確"
				render action: 'edit'
			end
		else
			flash[:error] = "您輸入的新密碼不一致"
			render action: 'edit'
		end
	end

protected
	def user_params
		params.require(:user).permit(:account, :name, :password, :password_confirmation)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		
	end
end

app/helpers/admin/logins_helper.rb
module Admin::LoginsHelper
	def sign_in(user) # 把用戶登入
		session[:login_token] = user.login_token
	end

	def signed_in? # 用戶登入了嗎
		!current_user.nil?
	end

	def current_user # 現在登入的用戶
		@current_user ||= User.find_by_login_token(session[:login_token])
	end

	def current_user?(user) # user是現在登入的用戶嗎
		current_user == user
	end

	def sign_out # 登出
		@current_user = nil
		session.delete(:login_token)
	end

	def authenticate_user
		unless signed_in?
			flash[:warning] = "請先登入"
			redirect_to new_admin_login_path
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
	def sidebar_categories
		@categories = Category.all
	end
end

app/helpers/category_products_helper.rb
module CategoryProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/common/_footer.html.erb
<!-- Footer -->
<footer class="container-fluid" style="margin-top: 250px;">
  <p class="text-center text-muted">Copyright ©2015 Vicnature
    <br>Design by Bikon
  </p>
</footer>


        

app/views/admin/common/_navbar.html.erb
<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
      <%= link_to "維多利亞網站管理平台", admin_categories_path, :class => "navbar-brand" %>
    </div>
        
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right"> 
        <!-- 判斷現在是否登入 -->
        <% if signed_in? %> 
          <li><%= link_to "#{current_user.name}"%></li>
          <li><%= link_to "修改密碼", edit_user_path(current_user) %></li>
          <li><%= link_to "登出", admin_login_path, method: "delete" %></li>
        <% else %>
          <li><%= link_to "登入", new_admin_login_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
    
  </div>
  <!-- /.container -->
</nav>

app/views/common/_footer.html.erb
<!-- Footer -->
<footer>
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <ul class="list-inline">
          <li>
            <a href="/welcome#">Home</a>
          </li>
          
          <li class="footer-menu-divider">&sdot;</li>
          
          <li>
            <a href="/welcome#about">About</a>
          </li>
          
          <li class="footer-menu-divider">&sdot;</li>
          
          <li>
            <a href="/welcome#products">Products</a>
          </li>
          
          <li class="footer-menu-divider">&sdot;</li>
          
          <li>
            <a href="/welcome#contact">Contact</a>
          </li>
        </ul>
        <p class="copyright text-muted small">Copyright &copy; VICTORIA 維多利亞有機生活館 2015. All Rights Reserved</p>
      </div>
      <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
  </div>
  <!-- /.container -->
</footer>

app/views/common/_navbar.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
  <div class="container topnav">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
      </button>
      <%= link_to "VICTORIA 維多利亞有機生活館", welcome_index_path, class: "navbar-brand topnav" %>      
    </div>
    
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <a href="/welcome#about">About</a>
        </li>
        <li>
          <a href="/welcome#products">Products</a>
        </li>
        <li>
          <a href="/welcome#contact">Contact</a>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>

app/views/common/_sidebar.html.erb
<!-- Sidebar -->
<div class="col-md-3">
	<br>
	<br>
  <div class="list-group">
		<% @categories.each do |category| %>
			<li class="list-group-item">
				<%= link_to "#{category.title}", category_products_path(category)%>
				<span class="badge"><%= category.products.count %> 項商品</span>
			</li>
		<% end %>
	</div>
	<!-- /.list-group -->
</div>
<!-- /.col-md-3 -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Vicnature</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
	<!-- 顯示alert -->
	<div class="container-fluid">   
	  <% if flash[:error].presence %>
      <div class="alert alert-danger alert-error">
        <%= flash[:error] %>
      </div>
    <% else %>
      <% flash.each do |key, value| %>
	      <div class="alert alert-<%= key %>">
	        <%= value %>
        </div>
      <% end %>
    <% end %>
	</div>

	<div class="container">
		<div class="row">
			<%= render "admin/common/navbar" %>
			<%= yield %>
		</div>
	</div>
	<%= render "admin/common/footer" %>
</body>
</html>

app/views/layouts/categories.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

	<title>Vicnature</title>
	<!-- Custom Fonts -->
	<link rel="stylesheet href="app/assets/stylesheets/font-awesome/css/font-awesome.min.css"">
  <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>

<body>
	<!-- 顯示alert -->
	<div class="container-fluid">   
    <% if flash[:error].presence %>
      <div class="alert alert-danger">
        <%= flash[:error] %>
      </div>
    <% else %>
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>">
	        <%= value %>
        </div>
      <% end %>
    <% end %>
	</div>
	
	<div class="banner-products">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <h2>商品專區</h2>
        </div>
      </div>
    </div>
	</div>

	<div class="container">
		<div class="row">
			<%= render "common/navbar" %>
			<%= render "common/sidebar" %>
			<%= yield %>
		</div>
	</div>
	<%= render "common/footer" %>
</body>
</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

	<title>Vicnature</title>
	<!-- Custom Fonts -->
	<link rel="stylesheet href="app/assets/stylesheets/font-awesome/css/font-awesome.min.css"">
  <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>	
</head>

<body>
	<!-- 顯示alert -->
	<div class="container-fluid">   
    <% if flash[:error].presence %>
      <div class="alert alert-danger">
        <%= flash[:error] %>
      </div>
    <% else %>
      <% flash.each do |key, value| %>
	      <div class="alert alert-<%= key %>">
          <%= value %>
        </div>
      <% end %>
	  <% end %>
	</div>

	<div class="container-fluid">
		<div class="row">
			<%= render "common/navbar" %>
			<%= yield %>
		</div>
	</div>
	<%= render "common/footer" %>
</body>
</html>