config/routes.rb
Rails.application.routes.draw do
  root :to => 'welcome#index'
  resources :welcome  
  
  resources :categories do
    resources :products, :controller => 'category_products'
  end
  
  resources :users

  namespace :admin do
    resource :login, only: [:new, :create, :destroy]
    resources :categories do
      resources :products, :controller => 'category_products'
    end
  end
  

end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/admin/category.rb
class Admin::Category < Category
end

app/models/admin/product.rb
class Admin::Product < Product
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products
	validates_presence_of :title
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	belongs_to :product
	has_attached_file :file, :style => {:medium => "300x300#", :thumb => "100x100#"}
	validates_attachment_content_type :file, :content_type => /\Aimage\/.*\Z/
end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :category
	has_many :photos
	
	# 商品圖片
	has_attached_file :image, :styles => {:medium => "300x300#", :thumb => "100x100#"}
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
	
	# 價錢須為整數
	validates_numericality_of :price, :only_integer => true
	validates_presence_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	before_save {self.login_token ||= Digest::SHA1.hexdigest(SecureRandom.urlsafe_base64.to_s)}
	validates :name, presence: true, length: {maximum: 15}
	validates :account, presence: true, length: {maximum: 15}, uniqueness: true
end

app/controllers/admin/category_products_controller.rb
class Admin::CategoryProductsController < ApplicationController
	before_action :authenticate_user
	before_action :find_admin_category

	def index
		@products = @admin_category.products
	end

	def show
		@product = @admin_category.products.find(params[:id])
	end

	def new
		@product = @admin_category.products.build
	end

	def create
		@product = @admin_category.products.build(product_params)
		if @product.save
	    flash[:success] = "已成功新增商品"	
	    redirect_to admin_category_products_path
		else
			flash[:error] = @product.errors.full_messages
			render :action => :new
		end
	end

	def edit
		@product = @admin_category.products.find(params[:id])
	end

	def update
		@product = @admin_category.products.find(params[:id])
		if @product.update(product_params)
			flash[:success] = "已成功修改商品"			
			redirect_to admin_category_products_path(@admin_category)
		else
			flash[:error] = @product.errors.full_messages
			render :action => :edit
		end
	end

	def destroy
		@product = @admin_category.products.find(params[:id])
		if @product.destroy
			flash[:success] = "已成功刪除商品"
			redirect_to admin_category_products_path
		else
			flash[:error] = @product.errors.full_messages
			redirect_to :back
		end
	end

protected
	def find_admin_category
		@admin_category = Category.find(params[:category_id])
	end

	def product_params
		params.require(:product).permit(:name, :description, :price, :image)
	end	
	
end

app/controllers/admin/logins_controller.rb
class Admin::LoginsController < ApplicationController
  def new

  end

  def create
  	@user = User.find_by_account(params[:login][:account])
  	# 用login這個form的email資料

  	if @user && @user.authenticate(params[:login][:password])
  	# 如果有找到這個user且password驗證成功就登入 
	    sign_in(@user)
      flash[:success] = "歡迎回來, #{@user.name}!"
      redirect_to admin_categories_path
  	else
		  flash[:error] = "您輸入的帳號/密碼有誤"
      render action: 'new'
  	end
  end

  def destroy
    sign_out
    flash[:success] = "您已成功登出"
    redirect_to welcome_index_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include Admin::LoginsHelper
  include CategoriesHelper
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :sidebar_categories
  layout "categories"
end

app/controllers/category_products_controller.rb
class CategoryProductsController < ApplicationController
	before_action :sidebar_categories
	before_action :find_category
	layout "categories"

	def index
		@products = @category.products.page(params[:page]).per(9)
	end

	def show
		@product = @category.products.find(params[:id])
	end

protected
	def find_category
		@category = Category.find(params[:category_id])
	end
	
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def show

	end

	def create
		@user = User.new(user_params)
		if @user.save
			flash[:success] = "Welcome, #{@user.name}!"
			redirect_to admin_categories_path
		else	
			flash[:error] = "There are #{@user.errors.count} errors, #{@user.errors.full_messages}" 
			render action: 'new'
		end
	end

	def edit
		
	end

	def update
		if params[:user][:new_password] == params[:user][:password_confirmation]
			if current_user.authenticate(params[:user][:password])
				current_user.password = params[:user][:new_password]
				if current_user.save
					flash[:success]	= "您已成功修改密碼"
					redirect_to admin_categories_path
				end
			else		
				flash[:error] = "您輸入的密碼不正確"
				render action: 'edit'
			end
		else
			flash[:error] = "您輸入的新密碼不一致"
			render action: 'edit'
		end
	end

protected
	def user_params
		params.require(:user).permit(:account, :name, :password, :password_confirmation)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		
	end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/category_products_helper.rb
module Admin::CategoryProductsHelper
end

app/helpers/admin/logins_helper.rb
module Admin::LoginsHelper
	def sign_in(user) # 把用戶登入
		session[:login_token] = user.login_token
	end

	def signed_in? # 用戶登入了嗎
		!current_user.nil?
	end

	def current_user # 現在登入的用戶
		@current_user ||= User.find_by_login_token(session[:login_token])
	end

	def current_user?(user) # user是現在登入的用戶嗎
		current_user == user
	end

	def sign_out # 登出
		@current_user = nil
		session.delete(:login_token)
	end

	def authenticate_user
		unless signed_in?
			flash[:warning] = "請先登入"
			redirect_to new_admin_login_path
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
	def sidebar_categories
		@categories = Category.all
	end
end

app/helpers/category_products_helper.rb
module CategoryProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/category_products/edit.html.erb
<div class= "col-md-offset-4 col-md-4">
	<h3>Admin > Categories > <%= @admin_category.title %> > <%= @product.name %> > Edit</h3>
	<br>
	
	<%= form_for @product, :url => admin_category_product_path(@admin_category, @product), :method => :patch, class: "form-horizontal" do |product|%>
		<div class="form-group">
			<%= product.label :name, "輸入商品名稱" %>	
			<%= product.text_field :name, class: "form-control", placeholder: "輸入商品名稱" %>
			<br>
			<%= product.label :description, "輸入商品敘述" %>
			<%= product.text_area :description, class: "form-control", placeholder: "輸入商品敘述" %>
			<br>
			<%= product.label :price, "輸入商品售價" %>
			<%= product.text_field :price, class: "form-control", placeholder: "輸入商品售價" %>
			<br>
			<%= product.label :image, "選擇商品圖片" %>
			<%= product.file_field :image, class: "form-control" %>
  	</div>
		
		<br>
		<%= product.submit "送出", class: "btn btn-success" %>
		<br>
		<br>
		<%= link_to "取消", admin_category_products_path, class: "btn btn-danger" %>
	<% end %>
</div>

app/views/admin/category_products/index.html.erb
<h3>Admin > <%= link_to "Categories", admin_categories_path %> > <%= @admin_category.title %></h3>
<%= link_to '新增類別商品', new_admin_category_product_path(@admin_category), class: "btn btn-success" %>
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th class="col-md-1">商品編號</th>
      <th class="col-md-1">商品名稱</th>
      <th class="col-md-6">商品敘述</th>
      <th class="col-md-2">商品縮圖</th>
      <th class="col-md-1">修改</th>
      <th class="col-md-1">刪除</th>
    </tr>
  </thead>
  
  <tbody>
  	<% @products.each do |product| %>
	    <tr>
	      <td><%= product.id %></td>
	      <td><%= link_to "#{product.name}", admin_category_product_path(@admin_category, product) %></td>
	      <td><%= product.description %></td>
	      <td><%= image_tag product.image.url(:thumb) %></td>
	      <td><%= link_to "修改", edit_admin_category_product_path(@admin_category, product) %></td>
	      <td><%= link_to "刪除", admin_category_product_path(@admin_category, product), :method => :delete, data: {confirm: "確定要刪除此商品？"} %></td>
	    </tr>
    <% end %>
  </tbody>
</table> 

app/views/admin/category_products/new.html.erb
<div class= "col-md-offset-4 col-md-4">
	<h3>Admin > Categories > <%= @admin_category.title %> > New</h3>
	<br>
	<%= form_for @product, :url => admin_category_products_path(@admin_category), class: "form-horizontal" do |product|%>
		<div class="form-group">
			<%= product.label :name, "輸入商品名稱" %>	
			<%= product.text_field :name, class: "form-control", placeholder: "輸入商品名稱", required: "true"%>
			<br>
			<%= product.label :description, "輸入商品敘述" %>
			<%= product.text_area :description, class: "form-control", placeholder: "輸入商品敘述" %>
			<br>
			<%= product.label :price, "輸入商品售價" %>
			<%= product.text_field :price, class: "form-control", placeholder: "輸入商品售價" %>
			<br>
			<%= product.label :image, "選擇商品圖片" %>
			<%= product.file_field :image, class: "form-control" %>
  	</div>

		<br>
		<%= product.submit "送出", class: "btn btn-success" %>
		<br>
		<br>
		<%= link_to "取消", admin_category_products_path(@admin_category), class: "btn btn-danger" %>
	<% end %>
</div>

app/views/admin/category_products/show.html.erb
<div class="col-md-offset-2 col-md-10">
	<h3>Admin > 
		<%= link_to "Categories", admin_categories_path %> >
		<%= link_to "#{@admin_category.title}", admin_category_products_path(@admin_category) %> > 
		<%= @product.name %>
		<%= link_to "修改", edit_admin_category_product_path(@admin_category, @product), class: "pull-right btn btn-success" %>
	</h3>
	<br>
	<div class="row">
		<div class="col-md-3">
			<%= image_tag @product.image.url, class: "img-thumbnail" %>
		</div> 

		<div class="col-md-7">
			
			<div class="panel panel-info">
				<div class="panel-heading">
					<h5>商品名稱</h5>					
				</div>
				<div class="panel-body">
					<h5><%= @product.name %></h5>
				</div>
			</div>

			<div class="panel panel-info">
				<div class="panel-heading">
					<h5>商品售價</h5>					
				</div>
				<div class="panel-body">
					<h5>$<%= @product.price %></h5>
				</div>
			</div>

			<div class="panel panel-info">
				<div class="panel-heading">
					<h5>商品敘述</h5>					
				</div>
				<div class="panel-body">
					<h5><%= @product.description %></h5>
				</div>
			</div>

		</div>	
		<!-- /.col-md-7 -->
	</div>		
	<!-- /.row -->
</div>
<!-- /.col-md-offset-2 -->

app/views/category_products/index.html.erb
<br>
<br>
<div class="col-md-9">
	<div class="row">
		<% @products.each do |p| %>
			<div class="col-md-4" >
				<div class="products-item">
					<%= image_tag p.image.url(:medium), class: "img-thumbnail"%>
	        <h4><%= link_to "#{p.name}", category_product_path(@category, p) %></h4>   
        </div>
        <!-- /.products-item -->
      </div>
      <!-- /.row -->
		<% end %>
	</div>
	<%= paginate @products %>
</div>
<!-- /.col-md-9 -->

app/views/category_products/show.html.erb
<br>
<br>
<div class="col-md-9">
	<table class="table table-bordered">
		<tbody>
			<tr>
				<td class="col-md-2"><h5>商品名稱</h5></td>
				<td class="col-md-10"><h5><%= @product.name %></h5></td>
			</tr>

			<tr>
				<td><h5>商品售價</h5></td>
				<td><h5>$ <%= @product.price %></h5></td>
			</tr>	
			
			<tr>
				<td><h5>商品敘述</h5></td>
				<td><h5><%= @product.description %></h5></td>
			</tr>		
			
			<tr>
				<td><h5>商品圖片</h5></td>
				<td><%= image_tag @product.image.url %></td>
			</tr>		
			</tbody>
	</table>
</div> 